services:
#    agile_training.example:
#        class: Agile\TrainingBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    form.type.calandar:
        class: Agile\TrainingBundle\Form\Type\CalandarType
        tags:
            - { name: form.type, alias: calandar  }