<?php

namespace Agile\TrainingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PersonalInformationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonalInformationRepository extends EntityRepository
{
}
